services:
  aula-app:
    container_name: aula-app
    build:
      context: ./docker/dev
    volumes:
      - .:/go/src
    ports:
      - 8080:8080
    command: make start
  
  aula-mongo:
    container_name: aula-mongo
    image: mongo:5.0.10
    volumes:
      - .database:/data/db
    ports:
      - 27017:27017


  aula-redis:
    container_name: aula-redis
    image: grokzen/redis-cluster:6.2.8
    environment:
      - IP=0.0.0.0
      - INITIAL_PORT=23000
    ports:
      - "23000-23005:23000-23005"